[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
runner = "espflash flash -b 115200 -p /dev/ttyACM0 --monitor" 
rustflags = ["-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = { value = "tag:v4.4.4" } 
ESP_IDF_TOOLS_INSTALL_DIR = { value = "global" }

